{% set version = '0.5-0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pbkrtest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pbkrtest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pbkrtest/pbkrtest_{{ version }}.tar.gz
  sha256: f56525488c6efe4a5cbf849bf9a82747041478605b166c29bad54e464e46f469

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix >=1.2.3
    - r-broom
    - r-dplyr
    - r-knitr
    - r-lme4 >=1.1.10
    - r-magrittr
    - r-numderiv
  run:
    - r-base
    - r-mass
    - r-matrix >=1.2.3
    - r-broom
    - r-dplyr
    - r-knitr
    - r-lme4 >=1.1.10
    - r-magrittr
    - r-numderiv

test:
  commands:
    - $R -e "library('pbkrtest')"           # [not win]
    - "\"%R%\" -e \"library('pbkrtest')\""  # [win]

about:
  home: https://people.math.aau.dk/~sorenh/software/pbkrtest/
  license: GPL-2.0-or-later
  summary: "Test in mixed effects models. Attention is on mixed effects models as implemented
    in the 'lme4' package. For linear mixed models, this package implements (1) a parametric
    bootstrap test, (2) a Kenward-Roger-typ modification of F-tests for linear mixed
    effects models and (3) a Satterthwaite-type modification of F-tests for linear mixed
    effects models. The package also implements a parametric bootstrap test for generalized
    linear mixed models.  The facilities of the package are documented in the paper
    by Halehoh and H\xF8jsgaard, (2012, <doi:10.18637/jss.v059.i09>).  Please see 'citation(\"pbkrtest\")'
    for citation details."
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pbkrtest
# Version: 0.5-0.1
# Title: Parametric Bootstrap, Kenward-Roger and Satterthwaite Based Methods for Test in Mixed Models
# Authors@R: c( person(given = "Ulrich", family = "Halekoh", email = "uhalekoh@health.sdu.dk", role = c("aut", "cph")), person(given = "Sren", family = "Hjsgaard", email = "sorenh@math.aau.dk", role = c("aut", "cre", "cph")) )
# Maintainer: Sren Hjsgaard <sorenh@math.aau.dk>
# Description: Test in mixed effects models. Attention is on mixed effects models as implemented in the 'lme4' package. For linear mixed models, this package implements (1) a parametric bootstrap test, (2) a Kenward-Roger-typ modification of F-tests for linear mixed effects models and (3) a Satterthwaite-type modification of F-tests for linear mixed effects models. The package also implements a parametric bootstrap test for generalized linear mixed models.  The facilities of the package are documented in the paper by Halehoh and Hjsgaard, (2012, <doi:10.18637/jss.v059.i09>).  Please see 'citation("pbkrtest")' for citation details.
# URL: https://people.math.aau.dk/~sorenh/software/pbkrtest/
# Depends: R (>= 3.5.0), lme4 (>= 1.1.10)
# Imports: broom, dplyr, magrittr, MASS, Matrix (>= 1.2.3), methods, numDeriv, parallel, knitr
# Encoding: UTF-8
# ZipData: no
# License: GPL (>= 2)
# ByteCompile: Yes
# RoxygenNote: 7.1.1
# LazyData: true
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-12-18 00:48:26 UTC; sorenh
# Author: Ulrich Halekoh [aut, cph], Sren Hjsgaard [aut, cre, cph]
# Repository: CRAN
# Date/Publication: 2020-12-18 07:30:09 UTC
