# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Br3Vft+7Mylm+oBJCvhlVbBS2QeDfA+1FbzKIVZEYJPiLJO02t4iUI0vaPK/vvZ/TGx3eGcOpcylT3QnvqW/Q/5pobaqF4eeJ0fNgTet0I1J4KBOjf72NZoVIAQ3fZMn+X4nIoPwe/rs2dX1C02WZrMEbAICOiKbwxGMbMajTgK5vDbz5qaUJDqC7webey7OS97cSDJ366SU4NdGMmyAzi7Y1qWS/edMxtDaSjA5lTJpEx0ZhMHaOpowGgC2WfrXRABl8fTWAqNkyeaCTUqW61nkUkLfMVDFTR/JMA7ZFmsyai2S/y0rl/qJynjYvTtJ5DtLTQALHaOYO8GLOEXc8Cz20k8Gn0R0sWbBzm43ZT3CcOq/MHg/LSCbzZt59aXcy5QfoDNYHYg5hJCwwltckPKyNPPbZY3TDLOcJT2Rzv4blxtvvbFvV8COE6e42qRecu4uXTDg9v2Vk10ISq5JQOkC6fjg0QB+odrJfP1RKrp0JDPAemCBRtoZkdailIdoouswf1bXHCTt8Q6IrVKlVGzmsErXK9KaYvjNFi70qI/4+3FZnVLeIihsx6wmB/w0rT+LwSucYtoJRjZTQ6Ue2yf48E3j17rvsE36aJ2h+sD9Goud1EMTYx6xUHJBlnh+RWy3aEAvdpBowB7aYs4jR7PH3Eaho8EyS7nvFhgv1fA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
