appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Br3Vft+7Mylm+oBJCvhlVbBS2QeDfA+1FbzKIVZEYJPiLJO02t4iUI0vaPK/vvZ/TGx3eGcOpcylT3QnvqW/Q/5pobaqF4eeJ0fNgTet0I1J4KBOjf72NZoVIAQ3fZMn+X4nIoPwe/rs2dX1C02WZrMEbAICOiKbwxGMbMajTgK5vDbz5qaUJDqC7webey7OS97cSDJ366SU4NdGMmyAzi7Y1qWS/edMxtDaSjA5lTJpEx0ZhMHaOpowGgC2WfrXRABl8fTWAqNkyeaCTUqW61nkUkLfMVDFTR/JMA7ZFmsyai2S/y0rl/qJynjYvTtJ5DtLTQALHaOYO8GLOEXc8Cz20k8Gn0R0sWbBzm43ZT3CcOq/MHg/LSCbzZt59aXcy5QfoDNYHYg5hJCwwltckPKyNPPbZY3TDLOcJT2Rzv4blxtvvbFvV8COE6e42qRecu4uXTDg9v2Vk10ISq5JQOkC6fjg0QB+odrJfP1RKrp0JDPAemCBRtoZkdailIdoouswf1bXHCTt8Q6IrVKlVGzmsErXK9KaYvjNFi70qI/4+3FZnVLeIihsx6wmB/w0rT+LwSucYtoJRjZTQ6Ue2yf48E3j17rvsE36aJ2h+sD9Goud1EMTYx6xUHJBlnh+RWy3aEAvdpBowB7aYs4jR7PH3Eaho8EyS7nvFhgv1fA=}
